url: "https://www.musicando.fr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Musicando
description: L’éducation musicale précoce au service des enfants des zones défavorisées
lang: fr

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - webpack.config.js
  - yarn.lock

plugins:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-include-cache

sass:
    style: compressed

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
  remove_comments: true
  compress_css: false
  compress_javascript: false
  uglifier_args:
    harmony: true

picture:
  ignore_missing_images: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    permalink: /:title
