backend:
  name: git-gateway
  branch: main

locale: fr

logo_url: /assets/images/logos/logo.svg

media_folder: 'assets/uploads'

markdown_light_button: &MARKDOWN_LIGHT_BUTTONS
  [bulleted-list, bold, italic, link]

menu_fields: &MENU_FIELDS
  - {label: "Title", name: "title", widget: "string"}
  - {label: "URL", name: "url", widget: "string"}

page_fields: &PAGE_FIELDS
  - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
  - { label: 'Title', name: 'title', widget: 'string' }
  - { label: 'Text', name: 'body', widget: 'markdown' }
  - label: Sections
    name: sections
    widget: 'list'
    fields:
      - { label: Image, name: image, widget: image }
      - { label: 'Text', name: text, widget: markdown }

collections:
  - name: 'pages'
    label: 'Pages'
    create: true
    fields: *PAGE_FIELDS
    folder: '_pages'
    identifier_field: name

  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: "Menus"
        name: "menu"
        file: "_data/menus.yml"
        fields:
          - label: "Primary menu"
            name: "primary"
            widget: "list"
            allow_add: false
            fields: *MENU_FIELDS
          - label: "Legal"
            name: "legal"
            widget: "list"
            allow_add: false
            fields: *MENU_FIELDS
          - label: "Social"
            name: "social"
            widget: "list"
            allow_add: false
            fields: *MENU_FIELDS
